name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: credentials.json の作成
        run: |
          mkdir -p ./terraform
          echo "${{ secrets.GCP_SA_KEY }}" > ./terraform/credentials.json
          ls -la ./terraform

      - name: credentials.json の存在確認
        run: test -f ./terraform/credentials.json

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT }}" -var="region=${{ secrets.GCP_REGION }}" -var="credentials_file=credentials.json"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT }}" -var="region=${{ secrets.GCP_REGION }}" -var="credentials_file=credentials.json"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform output
        working-directory: ./terraform
        run: terraform output cloud_run_url
